[브루트포스] 09월 21일
Altu-Bitu-3/Altu-Bitu-Minji pull request #5
Opened 2022-09-21 18:00 UTC by nitronium102

#### 내용 & 질문
> ex. 제출합니다!

#### <기존 제출>
> 1544, 2858

#### <추가 제출>
>

2022-09-22 17:19 UTC, bsa0322 requested changes
**p1. 2858 코드리뷰 완료**
민지님 안녕하세요 😊 코드 깔끔하게 함수화 해주셔서 너무 잘 봤습니다!! 

코드 효율성과 함수 내에서 출력 관련해 코멘트 남겼습니다! 확인 후, 질문사항이나 수정사항 생기면 리뷰어로 호출 부탁드려요~! 수고하셨습니다 🥰🥰🥰

2022-09-22 17:19 UTC, bsa0322 commented on 09월 16일 - 브루트포스/2858.cpp
> +                return 0;
p1. 출력은 가급적 main함수에서 진행해주시는 편이 좋아요!! 디버깅을 위한 출력 코드가 아닌 이상, **함수는 용도가 명확하게** (지금으로 예를 들면 가로와 세로 길이를 구하는 함수) 해서 **구한 정답은 리턴하는 형태**가 나중에 함수의 재활용도도 높아지고, 가독성도 높일 수 있습니다!! 
함수 내에 출력이 있다면, 나는 해당 함수에서 딱 정답만 구하고 싶은건데 계속 출력이 돼서 곤란한 상황이 생길 수도 있겠죠 😂

지금 함수화 해주신 거 좋지만, 위의 코멘트 참고해서 리턴형이 있도록 작성하면 좋을 것 같아요~! 값이 2개여서 리턴형이 애매하다면 **c++의 pair 클래스**에 대해 알아보셔도 좋을 것 같습니다 🥰

2022-09-22 17:19 UTC, bsa0322 commented on 09월 16일 - 브루트포스/2858.cpp
> +        for (int j = i; j >= 3; j--) {
p1. 가로, 세로 길이의 최소가 3이라는 점을 활용해서 브루트 포스적 접근을 아주 잘 해주셨네요!! 
지금도 좋지만, **해당 문제는 O(N) 으로 해결**할 수도 있어요.

깃허브 힌트로 **타일의 총 개수는 타일의 넓이**와 같을 거라 말씀드렸죠~! 저희는 직사각형의 넓이를 안다면, **가로와 세로 둘 중 하나의 길이만 알아도 다른 길이를 알 수가 있어요!** 그리고 가로와 세로 길이를 알면 지금처럼 빨간 타일과 갈색 타일의 개수를 구해 정답과 일치하는지 알 수 있겠죠 🥰 그리고 이때는, 직사각형의 넓이에 맞춰 가로와 세로의 길이를 구했을 테니까 **두 타일 중 하나만 비교해도 괜찮을 것 같아요.**

힌트 더 필요하시면 말씀해주세요~!

2022-09-24 11:03 UTC, jaeseo222 reviewed
**p2. 1544 코드 리뷰 완료**

안녕하세요 민지님 🦕🦕 리뷰를 늦게 드려 죄송합니다 ㅜㅜ
너무 잘 풀어주시고,, 함수화로 코드도 깔끔할 뿐더러 주석도 작성해주셔서 리뷰 드리기 너무 좋았습니다!!
간단한 코멘트 달았으니, 확인 부탁 드립니다 !
**수정하신 부분 있으시면 리뷰어로 불러주셔도 좋습니다!** 수고 많으셨습니다.
감사합니다.🤗🤗

2022-09-24 11:03 UTC, jaeseo222 commented on 09월 16일 - 브루트포스/1544.cpp
> +    }
참고해주시면 좋을 것 같아서 남깁니다!
`중복을 허용하지 않는 자료구조`가 있었죠! 서로 다른 단어를 담기에 아주 적합하겠어요. 이 자료구조는 **찾으려는 요소가 존재하는지 확인**하는 함수도 제공되기 때문에 활용해보셔도 좋을 것 같아요! 샘플 코드로 준비했으니, 참고해주셔도 좋을 것 같습니다 🤩🤩

2022-12-17 13:00 UTC, merged